name: my_events
description: Test task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  badges: 3.1.1
  collection: 1.17.0
  cupertino_icons: 1.0.5
  duration: 3.0.13
  flutter_bloc: 8.1.3
  flutter_hooks: 0.18.6
  flutter_svg: 2.0.2
  freezed_annotation: 2.4.1
  get_it: 7.6.0
  go_router: 10.0.0
  injectable: 2.1.2
  intl: 0.17.0
  lazy_load_scrollview: 1.3.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.3.3
  flutter_gen_runner: 5.3.1
  flutter_lints: 2.0.2
  freezed: 2.3.5
  injectable_generator: 2.1.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/mock/icons/
    - assets/mock/images/

  fonts:
    - family: Sansation
      fonts:
        - asset: assets/fonts/sansation/Sansation-Bold.ttf
        - asset: assets/fonts/sansation/Sansation-BoldItalic.ttf
        - asset: assets/fonts/sansation/Sansation-Italic.ttf
        - asset: assets/fonts/sansation/Sansation-Light.ttf
        - asset: assets/fonts/sansation/Sansation-LightItalic.ttf
        - asset: assets/fonts/sansation/Sansation-Regular.ttf

flutter_gen:
  integrations:
    flutter_svg: true